fs=require('fs')
sourcefolder='bookxml/';
outputfolder='xml/';
lst=fs.readFileSync('./pts.lst','utf8').replace(/\r\n/g,'\n').split('\n');

var footnotes=require('./data/footpg1.json'); //generated by footpgcsv2json.js
/*TODO
check if all footnote consumed by text
*/
var possiblefn=[];
var wrongpid=[];
var filenow="";
var nofootnote=[]; // text has foot note marker, but footnote not found 
var page=0,book=0,fnid=1;
var foundfncount=0;
parseParagraphid=function(line) {
	if (line[0]==" ") return parseInt(line,10);
}
hasfootnote=function(id) {
	bkpg=book+'.'+page;
	group=footnotes[bkpg];
	if (group && group[id-1]) return true;
	return false;
}
parseFootnote=function(line,linenum) {
	var i=0,out="",intag=false,inbracket=false;
	while (i<line.length) {
		if (line[i]=='<') intag=true;
		if (line[i]=='[') inbracket=true;
		if (!intag && !inbracket) {
			id=parseInt(line.substring(i),10);
			if (id>0 && id==fnid || id+1==fnid) { //same footnote number might happen more than once
				
				i+=id.toString().length;
				if (hasfootnote(id)) {
					out+='<fn n="'+id+'"/>';
					if (id==fnid) fnid++;
					foundfncount++;
					continue;
				} else {
					out+='<fn n="'+id+'" notfound=true/>';
					nofootnote.push(book+'.'+page+'='+id);
				}
			}
			if (id > 0) {
					possiblefn.push(filenow+':'+linenum+'='+page+':'+id);
			}
		}
		if (i>=line.length) break;
		if (line[i]=='>')intag=false;
		if (line[i]==']')inbracket=false;
		out+=line[i];
		i++;			
	}
	return out;
}

dofile=function(f){
	console.log('processing',f)
	var arr=fs.readFileSync(sourcefolder+f,'utf8').replace(/\r\n/g,'\n').split('\n');
	var out=[];
	var lastpid=0;
	for (var i=0;i<arr.length;i++) {
		var line=arr[i];
		if (line.substring(0,6)=='<book ') {
			book=parseInt(line.substring(9),10);
		}
		if (line.substring(0,4)=='<pb ') {
			page=parseInt(line.substring(7),10);
			fnid=1;
		}
		filenow=f;
		var pid=parseParagraphid(line);
		if (pid) {
			if (pid-1!=lastpid) {
				wrongpid.push(filenow+':'+i+'='+pid+' expect:'+(lastpid+1));
			}
			line=line.trim().substring(pid.toString().length+1);
			line='<p n="'+pid+'"/>'+line;
			lastpid=pid;
		}
		line=parseFootnote(line,i);
		out.push(line);
	}
	fs.writeFileSync(outputfolder+f,out.join('\n'),'utf8');
}
lst.map(function(file){dofile(file)});


fs.writeFileSync('./error/possiblefn.json',possiblefn.join('\n'),'utf8')
fs.writeFileSync('./error/wrongpid.json',wrongpid.join('\n'),'utf8')
fs.writeFileSync('./error/nofootnote.json',nofootnote.join('\n'),'utf8')
console.log('total foot note match',foundfncount)
console.log('missing foot note',nofootnote.length	)